config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users

  resources :stores
  root 'stores#index'

  namespace :seller do 
    root 'products#index'
    resources :products
    resources :settings
    resources :product_categories
  end

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
	has_many :store_product_categoryships
	has_many :stores, :through => :store_product_categoryships
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :product_categories, dependent: :destroy, :through => :store_product_categoryships
	has_many :store_product_categoryships
	mount_uploader :image, ImageUploader
end

app/models/store_product.rb
class StoreProduct < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/store_product_categoryship.rb
class StoreProductCategoryship < ActiveRecord::Base
	belongs_to :store
	belongs_to :product_category, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def login_required
    if current_user.blank?
      respond_to do |format|
        format.html {
          authenticate_user!
        }
        format.all {
          head(:unauthorized)
        }
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/seller/base_controller.rb
class Seller::BaseController < ApplicationController
	before_action :login_required, :required_seller!

	layout 'seller.html.erb'

	protected

	#判斷如果身分不是seller就無法進入賣家後台
	def required_seller!
		redirect_to stores_path, notice: '你沒有權限進入此頁面' unless current_user && current_user.seller?
	end
end

app/controllers/seller/product_categories_controller.rb
class Seller::ProductCategoriesController < Seller::BaseController
	before_action :mystorecategory, only: [:edit, :update]
	def index
		@store = Store.find_by_user_id(current_user.id)
		@product_categories = ProductCategory.where(store_id: @store.id)
	end

	def new
		@store = Store.find_by_user_id(current_user.id)
		@sid = @store.id
		@product_category = ProductCategory.new
	end

	def create
		@store = Store.find_by_user_id(current_user.id)
		@product_category = @store.product_categories.create(product_categories_params)
		if @product_category.save
			redirect_to seller_product_categories_path
		else
			render :new
		end
	end

	def edit
		@product_category = ProductCategory.find(params[:id])
		@store = Store.find_by_user_id(current_user.id)
		@sid = @store.id
	end

	def update
		@product_category = ProductCategory.find(params[:id])
		if @product_category.update(product_categories_params)
			redirect_to seller_product_categories_path
		else
			render :edit
		end
	end

	def destroy
		@product_category = ProductCategory.find(params[:id])
		@product_category.destroy

		redirect_to seller_product_categories_path
	end

	private
	def product_categories_params
		params.require(:product_category).permit(:name, :store_id)
	end

	def mystorecategory
		@store = Store.find_by_user_id(current_user.id)
 
		@productcategory = ProductCategory.find(params[:id])

		if @productcategory.store_id != @store.id
			redirect_to seller_products_path, notice: '您沒有這個分類'
		end
	end
end

app/controllers/seller/products_controller.rb
class Seller::ProductsController < Seller::BaseController
	before_action :myproduct, only: [:edit, :update]
	def index
		@store = Store.find_by_user_id(current_user.id)
		@products = StoreProduct.where(store_id: @store.id)
	end

	def new
		@store = Store.find_by_user_id(current_user.id)
		@sid = @store.id
		@product = StoreProduct.new
	end

	def create
		@product = StoreProduct.new(product_params)
		if @product.save
			redirect_to seller_products_path
		else
			render :new
		end
	end

	def edit
		@product = StoreProduct.find(params[:id])
	end

	def update
		@product = StoreProduct.find(params[:id])
		if @product.update(product_params)
			redirect_to seller_products_path
		else
			render :edit
		end
	end

	def destroy
		@product = StoreProduct.find(params[:id])
		@product.destroy

		redirect_to seller_products_path
	end

	private
	def product_params
		params.require(:store_product).permit(:name, :category, :store_id, :origin_price, :price, :size, :image, :content)
	end

	def myproduct
		@store = Store.find_by_user_id(current_user.id)
 
		@product = StoreProduct.find(params[:id])

		if @product.store_id != @store.id
			redirect_to seller_products_path, notice: '您沒有此商品'
		end
	end
end

app/controllers/seller/settings_controller.rb
class Seller::SettingsController < Seller::BaseController
	before_action :mystore, only: [:edit, :update]

	def index
		@settings = Store.where(user_id: current_user.id)
	end

	def edit
		@setting = Store.find(params[:id])
	end

	def update
		@setting = Store.find(params[:id])
		if @setting.update(setting_params)
			redirect_to seller_settings_path
		else
			render :edit
		end
	end

	private
	def setting_params
		params.require(:store).permit(:name, :tel, :address, :zip, :image)
	end

	def mystore
		@current_store = Store.find_by_user_id(current_user.id)

		@store = Store.find(params[:id])

		if @current_store.id != @store.id
			redirect_to seller_settings_path, notice: '找不到該店家'
		end
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	def index
		@stores = Store.all
	end

	def show
		@stores = Store.where(id: params[:id])
		@product_categories = ProductCategory.where(store_id: params[:id])
		@products = StoreProduct.where(store_id: params[:id])
	end

	private
	def store_params
		params.require(:store).permit(:name, :tel, :address, :zip, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seller/product_categories_helper.rb
module Seller::ProductCategoriesHelper
end

app/helpers/seller/products_helper.rb
module Seller::ProductsHelper
end

app/helpers/seller/settings_helper.rb
module Seller::SettingsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
	def count_product(id)
		@count = StoreProduct.where(store_id: id).count		
	end
end

app/views/common/_copyright.html.erb
<!--copy-right-->
    <div class="copy-right">
      <div class="container">
        <p>Template by <a href="http://w3layouts.com/">W3layouts</a></p>
        <script type="text/javascript">
            $(document).ready(function() {
              /*
              var defaults = {
                  containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear' 
              };
              */
              
              $().UItoTop({ easingType: 'easeOutQuart' });
              
            });
          </script>
        <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
      </div>
    </div>
<!--//copy-right-->

app/views/common/_footer.html.erb
<!--footer-->
<div class="footer">
  <div class="container">
    <div class="col-md-3 footer-logo">
      <a href="index.html"><img src="../assets/frontend/flogo.png" title="brand-logo" /></a>
    </div>
    <div class="col-md-7 footer-links">
      <ul class="unstyled-list list-inline">
        <li><a href="#"> Faq</a> <span> </span></li>
        <li><a href="#"> Terms and Conditions</a> <span> </span></li>
        <li><a href="#"> Secure Payments</a> <span> </span></li>
        <li><a href="#"> Shipping</a> <span> </span></li>
        <li><a href="contact.html"> Contact</a> </li>
        <div class="clearfix"> </div>
      </ul>
    </div>
    <div class="col-md-2 footer-social">
      <ul class="unstyled-list list-inline">
        <li><a class="pin" href="#"><span> </span></a></li>
        <li><a class="twitter" href="#"><span> </span></a></li>
        <li><a class="facebook" href="#"><span> </span></a></li>
        <div class="clearfix"> </div>
      </ul>
    </div>
    <div class="clearfix"> </div>
  </div>
 </div>
 <div class="clearfix"> </div>
<!--//footer-->

app/views/common/_header.erb
<!--top-header-->
<div class="top-header">
  <div class="logo">
    <%= link_to root_path do %>
      <img src="../assets/frontend/logo.png" title="barndlogo" />
    <% end %>
  </div>
  <div class="top-header-info">
    <div class="top-contact-info">
      <ul class="unstyled-list list-inline">
        <li><span class="phone"> </span>090 - 223 44 66</li>
        <li><span class="mail"> </span><a href="#">help@trendd.com</a></li>
        <div class="clearfix"> </div>
      </ul>
    </div>
    <div class="cart-details">
      <div class="add-to-cart">
        <ul class="unstyled-list list-inline">
          <li><span class="cart"> </span>
            <ul class="cart-sub">
              <li><p>0 Products</p></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="login-rigister">
        <ul class="unstyled-list list-inline">
        	<% if user_signed_in? && current_user.admin? %>
	        	<li><%= link_to '後台', seller_products_path, :class => 'login' %></li>
	          <li><%= link_to '個人資料', edit_user_registration_path, :class => 'login' %></li>
	          <li><%= link_to "登出", destroy_user_session_path, method: :delete, :class => 'login' %></li>
          <% elsif user_signed_in? && current_user.seller? %>
<li class="dropdown hidden-xs">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-user padding-right-small" style="position:relative;top: 3px;"></span><%= current_user.name %>
            <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu">
        	<li><%= link_to '後台', seller_products_path %></li>
          <li><%= link_to '個人資料', edit_user_registration_path %></li>
          <li><%= link_to "登出", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
	        <% elsif user_signed_in? %>  
          	<li><%= link_to '個人資料', edit_user_registration_path, :class => 'login' %></li>
	          <li><%= link_to "登出", destroy_user_session_path, method: :delete, :class => 'login' %></li>
          <% else %>
          	<li><%= link_to "會員註冊", new_user_registration_path, :class => 'login'  %></li>
      	    <li><%= link_to new_user_session_path, :class => 'rigister' do %>
          			登入<span></span>
          	<% end %>
          <% end %>
          </li>
          <div class="clearfix"> </div>
        </ul>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
  <div class="clearfix"> </div>
</div>
<!--//top-header-->

app/views/common/_menu.html.erb
<div class="col-md-2">
	<ul class="active">
	<li><%= link_to '商品管理', seller_products_path %></li>
	<li><%= link_to '商品分類', seller_product_categories_path %></li>
	<li><%= link_to '設定', seller_settings_path %></li>
	</ul>
</div>

app/views/common/_navbar.html.erb
<!---top-header-nav-->
  <div class="top-header-nav"> 
  <!--start-top-nav-->
   <nav class="top-nav main-menu">
      <ul class="top-nav">
        <li><a href="products.html">PRODUCTS </a><span> </span></li>
        <li><a href="products.html">CAMPAINGS</a><span> </span></li>
        <li><a href="products.html">SERVICES</a><span> </span></li>
        <li><a href="products.html">BRANDS</a><span> </span></li>
        <li><a href="products.html">ABOUT US</a></li>
        <div class="clearfix"> </div>
      </ul>
      <a href="#" id="pull"><img src="../assets/frontend/nav-icon.png" title="menu" /></a>
    </nav>
    <!--End-top-nav-->
    <!--top-header-search-box-->
    <div class="top-header-search-box">
      <form>
        <input type="text" placeholder="Search" required / maxlength="22">
        <input type="submit" value=" " >
      </form>
    </div>
    <!--top-header-search-box-->
        <div class="clearfix"> </div>
  </div>
</div>
<!--//top-header-nav-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--container-->
<div class="container">      
  <%= render 'common/header' %>
  <%= render 'common/navbar' %>
	<%= yield %>
</div>
<!--container-->

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= render 'common/footer' %>
<%= render 'common/copyright' %>

</body>
</html>

app/views/seller/product_categories/edit.html.erb
<div class="content">
  <div class="header">    
      <h1 class="page-title">分類編輯</h1>
      <ul class="breadcrumb">
        <li><%= link_to('首頁', seller_products_path) %></li>
        <li><%= link_to('商品分類', seller_product_categories_path) %></li>
        <li class="active"><%= @product_category.name %></li>
    </ul>
  </div>
  <%= bootstrap_form_for @product_category, url: seller_product_category_path(@product_category) do |e| %>
  <div class="main-content">            
    <div class="row">
      <div class="col-md-4">
        <%= e.text_field :name %>
        <%= e.hidden_field :store_id, value: @sid %>
        <div class="btn-toolbar list-toolbar">
          <%= e.submit '更新', class: :"btn btn-primary" %>
          <%= link_to('返回', seller_product_categories_path, class: :"btn btn-primary") %>
          <a href="#<%= @product_category.id %>" data-toggle="modal" class="btn btn-danger">Delete</a>
        </div>        
        <div class="modal small fade" id="<%= @product_category.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">Delete Confirmation</h3>
              </div>
              <div class="modal-body">              
                <p class="error-text"><i class="fa fa-warning modal-icon"></i>Are you sure you want to delete <%= @product_category.name %>?</p>
              </div>
              <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <%= link_to('Delete', seller_product_category_path(@product_category), class: :"btn btn-danger", data: {dismiss: "modal"}, method: :delete) %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <footer>
     <hr>
    <!-- Purchase a site license to remove this link from the footer: http://www.portnine.com/bootstrap-themes -->
    <p class="pull-right">A <a href="http://www.portnine.com/bootstrap-themes" target="_blank">Free Bootstrap Theme</a> by <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
    <p>© 2014 <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
  </footer>
</div>


app/views/seller/product_categories/index.html.erb
<div class="content">
  <div class="header">      
    <h1 class="page-title">商品</h1>
            <ul class="breadcrumb">
    <li><%= link_to('首頁', seller_products_path) %></li>    
    <li class="active">商品分類</li>
  </ul>
  </div> 
  <div class="main-content">
  <div class="btn-toolbar list-toolbar">
    <%= link_to new_seller_product_category_path, class: :"btn btn-primary" do %>
      <i class="fa fa-plus">新增分類</i>
    <% end %>
  </div> 

  <table class="table">   
    <thead>
      <tr>
        <th>類別名稱</th>
        <th>創建日期</th>
        <th style="width: 3.5em;"></th>
      </tr>
    </thead>
    <% @product_categories.each do |i| %>
    <tbody>
      <tr>
        <td><%= i.name %></td>
        <td><%= i.created_at %></td>
        <td>
            <%= link_to edit_seller_product_category_path(i) do %>
              <i class="fa fa-pencil"></i>
            <% end %>            
            <a href="#<%= i.id %>" role="button" data-toggle="modal"><i class="fa fa-trash-o"></i></a>            
        </td>
      </tr>
    </tbody>
    <div class="modal small fade" id="<%= i.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h3 id="myModalLabel">Delete Confirmation</h3>
          </div>
          <div class="modal-body">
              <p class="error-text"><i class="fa fa-warning modal-icon"></i>Are you sure you want to delete <%= i.name %>?</p>
          </div>
          <div class="modal-footer">
              <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
              <%= link_to('Delete', seller_product_category_path(i), class: :"btn btn-danger", data: {dismiss: "modal"}, method: :delete) %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </table>

  <footer>
      <hr>
      <!-- Purchase a site license to remove this link from the footer: http://www.portnine.com/bootstrap-themes -->
      <p class="pull-right">A <a href="http://www.portnine.com/bootstrap-themes" target="_blank">Free Bootstrap Theme</a> by <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
      <p>© 2014 <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
  </footer>
</div>


app/views/seller/products/edit.html.erb
<div class="content">
  <div class="header">    
      <h1 class="page-title">商品編輯</h1>
      <ul class="breadcrumb">
        <li><%= link_to('首頁', seller_products_path) %></li>
        <li><%= link_to('商品管理', seller_products_path) %></li>
        <li class="active"><%= @product.name %></li>
    </ul>
  </div>
  <%= bootstrap_form_for @product, url: seller_product_path(@product) do |e| %>
  <div class="main-content">            
    <div class="row">
      <div class="col-md-4">
        <%= e.text_field :name %>
        <%= e.text_field :origin_price %>
        <%= e.text_field :price %>
        <%= e.text_field :size %>  
        <%= e.file_field :image %>
      </div>
      <div class="col-md-7">
        <%= e.text_area :content, :class => "redactor", :rows => 40, :cols => 120 %>      
        <div class="btn-toolbar list-toolbar">
          <%= e.submit '保存', class: :"btn btn-primary" %>
          <%= link_to('返回', seller_products_path, class: :"btn btn-primary") %>
          <a href="#<%= @product.id %>" data-toggle="modal" class="btn btn-danger">Delete</a>
        </div>        
        <div class="modal small fade" id="<%= @product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">Delete Confirmation</h3>
              </div>
              <div class="modal-body">              
                <p class="error-text"><i class="fa fa-warning modal-icon"></i>Are you sure you want to delete <%= @product.name %>?</p>
              </div>
              <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <%= link_to('Delete', seller_product_path(@product), class: :"btn btn-danger", data: {dismiss: "modal"}, method: :delete) %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <footer>
     <hr>
    <!-- Purchase a site license to remove this link from the footer: http://www.portnine.com/bootstrap-themes -->
    <p class="pull-right">A <a href="http://www.portnine.com/bootstrap-themes" target="_blank">Free Bootstrap Theme</a> by <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
    <p>© 2014 <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
  </footer>
</div>


app/views/seller/products/index.html.erb
<div class="content">
  <div class="header">      
    <h1 class="page-title">商品</h1>
            <ul class="breadcrumb">
    <li><%= link_to('首頁', seller_products_path) %></li>    
    <li class="active">商品管理</li>
  </ul>
  </div> 
  <div class="main-content">
  <div class="btn-toolbar list-toolbar">
    <%= link_to new_seller_product_path, class: :"btn btn-primary" do %>
      <i class="fa fa-plus">新增商品</i>
    <% end %>
  </div> 

  <table class="table">   
    <thead>
      <tr>
        <th>商品圖</th>
        <th>商品名稱</th>
        <th>創建日期</th>
        <th style="width: 3.5em;"></th>
      </tr>
    </thead>
    <% @products.each do |i| %>
    <tbody>
      <tr>
        <td><%= image_tag i.image_url(:small)   %></td>
        <td><%= i.name %></td>
        <td><%= i.created_at %></td>
        <td>
            <%= link_to edit_seller_product_path(i) do %>
              <i class="fa fa-pencil"></i>
            <% end %>            
            <a href="#<%= i.id %>" role="button" data-toggle="modal"><i class="fa fa-trash-o"></i></a>            
        </td>
      </tr>
    </tbody>
    <div class="modal small fade" id="<%= i.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h3 id="myModalLabel">Delete Confirmation</h3>
          </div>
          <div class="modal-body">
              <p class="error-text"><i class="fa fa-warning modal-icon"></i>Are you sure you want to delete <%= i.name %>?</p>
          </div>
          <div class="modal-footer">
              <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
              <%= link_to('Delete', seller_product_path(i), class: :"btn btn-danger", data: {dismiss: "modal"}, method: :delete) %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </table>

  <footer>
      <hr>
      <!-- Purchase a site license to remove this link from the footer: http://www.portnine.com/bootstrap-themes -->
      <p class="pull-right">A <a href="http://www.portnine.com/bootstrap-themes" target="_blank">Free Bootstrap Theme</a> by <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
      <p>© 2014 <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
  </footer>
</div>


app/views/seller/settings/edit.html.erb
<div class="content">
  <div class="header">    
      <h1 class="page-title">商店設定</h1>
      <ul class="breadcrumb">
        <li><%= link_to('首頁', seller_products_path) %></li>
        <li><%= link_to('設定', seller_settings_path) %></li>
        <li class="active"><%= @setting.name %></li>
    </ul>
  </div>
  <%= bootstrap_form_for @setting, url: seller_setting_path(@setting) do |e| %>
  <div class="main-content">            
    <div class="row">
      <div class="col-md-4">
        <%= e.text_field :name %>
        <%= e.text_field :tel %>
        <%= e.text_field :address %>
        <%= e.text_field :zip %>
        <%= e.file_field :image %>
        <div class="btn-toolbar list-toolbar">
          <%= e.submit '保存', class: :"btn btn-primary" %>
          <%= link_to('返回', seller_settings_path, class: :"btn btn-primary") %>          
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <footer>
     <hr>
    <!-- Purchase a site license to remove this link from the footer: http://www.portnine.com/bootstrap-themes -->
    <p class="pull-right">A <a href="http://www.portnine.com/bootstrap-themes" target="_blank">Free Bootstrap Theme</a> by <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
    <p>© 2014 <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
  </footer>
</div>


app/views/seller/settings/index.html.erb
<div class="content">
  <div class="header">      
    <h1 class="page-title">設定</h1>
            <ul class="breadcrumb">
    <li><%= link_to('首頁', seller_products_path) %></li>    
    <li class="active">設定</li>
  </ul>
  </div> 
  <div class="main-content">
  <table class="table">   
    <thead>
      <tr>
        <th>商家圖片</th>
        <th>商店名稱</th>
        <th>電話</th>
        <th>地址</th>
        <th>郵遞區號</th>
        <th>申請開店日期</th>
        <th>編輯資料</th>
        <th style="width: 3.5em;"></th>
      </tr>
    </thead>
    <% @settings.each do |i| %>
    <tbody>
      <tr>
        <td><%= image_tag i.image_url(:small) %></td>
        <td><%= i.name %></td>
        <td><%= i.tel %></td>
        <td><%= i.address %></td>
        <td><%= i.zip %></td> 
        <td><%= i.created_at %></td>
        <td>
            <%= link_to edit_seller_setting_path(i) do %>
              <i class="fa fa-pencil"></i>
            <% end %>
        </td>
      </tr>
    </tbody>
  <% end %>
  </table>

  <footer>
      <hr>
      <!-- Purchase a site license to remove this link from the footer: http://www.portnine.com/bootstrap-themes -->
      <p class="pull-right">A <a href="http://www.portnine.com/bootstrap-themes" target="_blank">Free Bootstrap Theme</a> by <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
      <p>© 2014 <a href="http://www.portnine.com" target="_blank">Shoes</a></p>
  </footer>
</div>


app/views/stores/index.html.erb
<%= render 'common/slidershow' %>
<!--content-->
<div class="content">
  <div class="container">
        <!--top-row-->
        <div class="top-row">
        <% @stores.each do |i| %>
          <div class="col-xs-4">
            <div class="top-row-col1 text-center">
              <h2><%= i.name %></h2>
              <%= image_tag i.image_url(:store), class: :"r-img text-center" do %>
              <% end %>
              <span><img src="../assets/frontend/obj1.png" title="name" /></span>
              <h4>TOTAL</h4>
              <label><%= count_product(i.id) %></label>
              <%= link_to store_path(i), class: :"r-list-w" do %>
                <img src="../assets/frontend/list-icon.png" title="list" />
              <% end %>
            </div>
          </div>
          <% end %>
          <div class="clearfix"> </div>
        </div>    
      <div class="clearfix"> </div>
  </div>
  <!--top-row-->
  </div>
<!--content-->